set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(TOOLCHAIN_PREFIX arm-none-eabi)
find_program(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
find_program(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy)
find_program(CMAKE_SIZE ${TOOLCHAIN_PREFIX}-size)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(MCPU_FLAGS "-mcpu=cortex-m0 -mthumb")
set(WARN_FLAGS "-Wall -Wextra -Wundef -Wshadow -Wdouble-promotion -Wformat=2 -Wno-unused-parameter")
set(CMAKE_C_FLAGS "${MCPU_FLAGS} -Os -ffunction-sections -fdata-sections -fno-common -fno-builtin ${WARN_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${MCPU_FLAGS} -Wl,--gc-sections -Wl,-Map=${CMAKE_PROJECT_NAME}.map -T ${CMAKE_SOURCE_DIR}/ld/lpc1114_32k_4k.ld -nostartfiles")
